/* SCHD equity membership seed from Schwab Asset Management all-holdings, as of 2026-08-06.
   Cash, money-market and futures rows are excluded from the stock universe. */
const SCHD_SEED={asOf:'2026-08-06',source:'Schwab Asset Management',holdings:[
  ['ABT','Abbott Laboratories'],['AMGN','Amgen Inc'],['MRK','Merck & Co Inc'],['HD','Home Depot'],['KO','Coca-Cola'],['UNH','UnitedHealth Group Inc'],['PG','Procter & Gamble'],['VZ','Verizon Communications Inc'],['CVX','Chevron Corp'],['PEP','PepsiCo Inc'],
  ['COP','ConocoPhillips'],['TXN','Texas Instruments Inc'],['BMY','Bristol Myers Squibb'],['LMT','Lockheed Martin Corp'],['MO','Altria Group Inc'],['ADP','Automatic Data Processing Inc'],['ACN','Accenture PLC Class A'],['BX','Blackstone'],['QCOM','Qualcomm'],['CMCSA','Comcast Class A'],
  ['SLB','SLB NV'],['UPS','United Parcel Service Inc Class B'],['EOG','EOG Resources'],['TGT','Target Corp'],['FAST','Fastenal'],['OKE','ONEOK'],['F','Ford Motor'],['FITB','Fifth Third Bancorp'],['DVN','Devon Energy'],['PAYX','Paychex'],
  ['ADM','Archer Daniels Midland'],['KMB','Kimberly-Clark'],['ARES','Ares Management Class A'],['CINF','Cincinnati Financial'],['HSY','Hershey Foods'],['RF','Regions Financial'],['TROW','T Rowe Price Group'],['DRI','Darden Restaurants Inc'],['PFG','Principal Financial Group Inc'],['SNA','Snap-on Inc'],
  ['GIS','General Mills Inc'],['BR','Broadridge Financial Solutions Inc'],['EWBC','East West Bancorp'],['BBY','Best Buy'],['FNF','Fidelity National Financial Inc'],['APA','APA'],['DINO','HF Sinclair'],['WSO','Watsco'],['AFG','American Financial Group'],['SWKS','Skyworks Solutions'],
  ['ORI','Old Republic International'],['COLB','Columbia Banking System Inc'],['BAH','Booz Allen Hamilton Holding Class A'],['ALV','Autoliv'],['M','Macys Inc'],['ERIE','Erie Indemnity Class A'],['MSM','MSC Industrial Class A'],['NXST','Nexstar Media Group Inc'],['OZK','Bank OZK'],['MTN','Vail Resorts'],
  ['MC','Moelis Class A'],['FHI','Federated Hermes Inc Class B'],['MUR','Murphy Oil Corp'],['KFY','Korn Ferry'],['RHI','Robert Half Inc'],['PAG','Penske Automotive Group Voting Inc'],['CWEN','Clearway Energy Inc Class C'],['CVBF','CVB Financial Corp'],['APAM','Artisan Partners Asset Management'],['BANR','Banner Corp'],
  ['CNS','Cohen & Steers Inc'],['WU','Western Union'],['MZTI','Marzetti'],['OFG','OFG Bancorp'],['AGM','Federal Agricultural Mortgage Non-Voting'],['IPAR','Interparfums Inc'],['CHCO','City Holding'],['NBHC','National Bank Holdings Corp Class A'],['GABC','German American Bancorp Inc'],['STBA','S&T Bancorp Inc'],
  ['NSP','Insperity'],['SRCE','1st Source Corp'],['LKFN','Lakeland Financial Corp'],['FLO','Flowers Foods Inc'],['BKE','Buckle'],['WEN','Wendys'],['PFBC','Preferred Bank'],['CNA','CNA Financial Corp'],['VRTS','Virtus Investment Partners Inc'],['CPF','Central Pacific Financial Corp'],
  ['THFF','First Financial Corp'],['HAFC','Hanmi Financial Corp'],['ORRF','Orrstown Financial Services Inc'],['IBCP','Independent Bank Corp'],['CCBG','Capital City Bank Inc'],['EBF','Ennis Inc'],['AMSF','AMERISAFE Inc'],['ETD','Ethan Allen Interiors'],['OXM','Oxford Industries Inc']
].map(([ticker,name])=>({ticker,name}))};
window.SCHD_SEED=SCHD_SEED;
